import unittest
import pandas as pd


class TestDataframe(unittest.TestCase):
    def test1(self):
        name_paavo_dataframe = "./dataframes/final_dataframe.tsv"
        df = pd.read_table(name_paavo_dataframe, dtype={"Postal code": object})
        names = ['Postal code', 'Free-time residences', 'Buildings, total', 'Other buildings', 'Residential buildings',
                 'Dwellings', 'Average floor area', 'Dwellings in small houses', 'Dwellings in blocks of flats',
                 'Aged 18 or over, total', 'Basic level studies', 'With education, total', 'Matriculation examination',
                 'Vocational diploma', 'Academic degree - Lower level university degree',
                 'Academic degree - Higher level university degree', 'Inhabitants, total', 'Inhabitants aged 18-64',
                 'Employment rate %', 'Unemployment rate %', 'Economic dependency ratio', 'Inhabitants, total.1',
                 'Females', 'Males', 'Average age of inhabitants', 'Households, total', 'Average size of households',
                 'Occupancy rate', 'Young single persons', 'Young couples without children', 'Households with children',
                 'Households with small children', 'Households with children under school age',
                 'Households with school-age children', 'Households with teenagers', 'Adult households',
                 'Pensioner households', 'Households living in owner-occupied dwellings',
                 'Households living in rented dwellings', 'Households living in other dwellings', 'Area', 'Density',
                 'Surface area', '0-15 years', '16-34 years', '35-64 years', '65 years or over',
                 'Average income of households', 'Median income of households',
                 'Households belonging to the lowest income category',
                 'Households belonging to the middle income category',
                 'Households belonging to the highest income category', 'Accumulated purchasing power of households',
                 'Average income of inhabitants', 'Median income of inhabitants',
                 'Inhabintants belonging to the lowest income category',
                 'Inhabitants belonging to the middle income category',
                 'Inhabintants belonging to the highest income category', 'Accumulated purchasing power of inhabitants',
                 'Inhabitants', 'Employed', 'Unemployed', 'Children aged 0 to 14', 'Students', 'Pensioners', 'Others',
                 'Workplaces', 'Primary production', 'Processing', 'Services', 'A Agriculture, forestry and fishing',
                 'B Mining and quarrying', 'C Manufacturing', 'D Electricity, gas, steam and air conditioning supply',
                 'E Water supply; sewerage, waste management and remediation activities', 'F Construction',
                 'G Wholesale and retail trade; repair of motor vehicles and motorcycles',
                 'H Transportation and storage', 'I Accommodation and food service activities',
                 'J Information and communication', 'K Financial and insurance activities', 'L Real estate activities',
                 'M Professional, scientific and technical activities',
                 'N Administrative and support service activities',
                 'O Public administration and defence; compulsory social security', 'P Education',
                 'Q Human health and social work activities', 'R Arts, entertainment and recreation',
                 'S Other service activities',
                 'T Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use',
                 'U Activities of extraterritorial organisations and bodies', 'X Industry unknown', 'Males scaled',
                 'Females scaled', 'Average age of inhabitants scaled', '0-15 years scaled', '16-34 years scaled',
                 '35-64 years scaled', '65 years or over scaled', 'Aged 18 or over, total scaled',
                 'Basic level studies scaled', 'With education, total scaled', 'Matriculation examination scaled',
                 'Vocational diploma scaled', 'Academic degree - Lower level university degree scaled',
                 'Academic degree - Higher level university degree scaled', 'Average size of households scaled',
                 'Young single persons scaled', 'Households with children scaled',
                 'Households with small children scaled', 'Households with children under school age scaled',
                 'Households with school-age children scaled', 'Households with teenagers scaled',
                 'Adult households scaled', 'Pensioner households scaled',
                 'Households living in owner-occupied dwellings scaled', 'Households living in rented dwellings scaled',
                 'Households living in other dwellings scaled', 'Other buildings scaled',
                 'Residential buildings scaled', 'Dwellings in small houses scaled',
                 'Dwellings in blocks of flats scaled', 'Inhabintants belonging to the lowest income category scaled',
                 'Inhabitants belonging to the middle income category scaled',
                 'Inhabintants belonging to the highest income category scaled', 'Students scaled',
                 'Households belonging to the lowest income category scaled',
                 'Households belonging to the middle income category scaled',
                 'Households belonging to the highest income category scaled', 'Primary production combine scaled',
                 'Processing combine scaled', 'Services combine scaled',
                 'A Agriculture, forestry and fishing combine scaled', 'B Mining and quarrying combine scaled',
                 'C Manufacturing combine scaled',
                 'D Electricity, gas, steam and air conditioning supply combine scaled',
                 'E Water supply; sewerage, waste management and remediation activities combine scaled',
                 'F Construction combine scaled',
                 'G Wholesale and retail trade; repair of motor vehicles and motorcycles combine scaled',
                 'H Transportation and storage combine scaled',
                 'I Accommodation and food service activities combine scaled',
                 'J Information and communication combine scaled',
                 'K Financial and insurance activities combine scaled', 'L Real estate activities combine scaled',
                 'M Professional, scientific and technical activities combine scaled',
                 'N Administrative and support service activities combine scaled',
                 'O Public administration and defence; compulsory social security combine scaled',
                 'P Education combine scaled', 'Q Human health and social work activities combine scaled',
                 'R Arts, entertainment and recreation combine scaled', 'S Other service activities combine scaled',
                 'T Activities of households as employers; undifferentiated goods- and services-producing activities of households for own use combine scaled',
                 'U Activities of extraterritorial organisations and bodies combine scaled', 'Bus stops',
                 'Metro', 'Train', 'Ferry', 'Tram', 'Bus', 'Sell price',
                 'Rent price with ARA', 'Rent price without ARA', 'Trend from 2018', 'Trend near future', 'Forest',
                 'Water', 'Boolean sea', 'Lat', 'Lon', 'Radius', 'text', 'label']

        self.assertEqual(df.shape[0], 3026)
        self.assertEqual(list(df.columns), names)


if __name__ == '__main__':
    unittest.main()
